# Generated by Django 2.1 on 2018-08-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path_to_config', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='NNTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=1000)),
            ],
        ),
    ]
