# Generated by Django 2.1 on 2018-08-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neural_network_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NNTask',
            new_name='Task',
        ),
    ]
