# Generated by Django 2.1 on 2018-08-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neural_network_service', '0002_auto_20180822_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='pid',
            new_name='celery_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='state',
        ),
    ]
